### ISSUE TITLE
npm ERR! code EISGIT, Appears to be a git repo or submodule on Heroku

### ISSUE THREAD

**Issue by benbowler** [gkozlenko/sequelize-tokenify#1]
Thanks for the package, it's come in handy, however, I've had [issues deploying to Heroku as with this thread](https://github.com/react-native-community/react-native-safe-area-view/issues/73). Can you resubmit the package to `npm` *removing the .git directory!*

Happy to help but this one requires access to npm, not something that can be submitted via a pr.

**Comment by gkozlenko** [comment]
Hello,

Thank you for your help. I've published a new version 0.2.2 without `.git` directory.
